#######################################################################################
# Book settings
title: Data Stewards' Book of Experiences
author: "4TU.ResearchData Community"
copyright: "2021"

#######################################################################################
# Launch button settings
repository: 
    url: https://github.com/NZR/DS-BOK

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : "off"  #Must be one of ("auto", "force", "cache", "off")

only_build_toc_files: true
exclude_patterns            : [_build, Thumbs.db, .DS_Store]
